FROM dockerfile/nodejs

WORKDIR /home/sf-bike-dock

# Install Prerequisites
RUN npm install -g grunt-cli
RUN npm install -g bower

# Install packages
ADD package.json /home/sf-bike-dock/package.json
RUN npm install

# Manually trigger bower. Why doesnt this work via npm install?
ADD .bowerrc /home/sf-bike-dock/.bowerrc
ADD bower.json /home/sf-bike-dock/bower.json
RUN bower install --config.interactive=false --allow-root

# Make everything available for start
ADD . /home/sf-bike-dock

# currently only works for development...
ENV NODE_ENV development

# Port 3000 for server
# Add Port 35729 for livereload
EXPOSE 3000
CMD ["grunt"]
