FROM node:0.10
#FROM dockerfile/nodejs

WORKDIR /home/sf-bike-dock

# Install Prerequisites
RUN npm install -g grunt-cli
RUN npm install -g bower

# Install packages
ADD package.json /home/sf-bike-dock/package.json
RUN npm install

# Manually trigger bower. Why doesnt this work via npm install?
ADD .bowerrc /home/sf-bike-dock/.bowerrc
ADD bower.json /home/sf-bike-dock/bower.json
RUN bower install --config.interactive=false --allow-root

# Make everything available for start
ADD app /home/sf-bike-dock/app/
ADD config /home/sf-bike-dock/config/
ADD server.js /home/sf-bike-dock/

ADD public/js /home/sf-bike-dock/public/js/
ADD public/modules /home/sf-bike-dock/public/modules/
# ADD public/application.js /home/sf-bike-dock/public/
ADD public/config.js /home/sf-bike-dock/public/
ADD public/humans.txt /home/sf-bike-dock/public/
ADD public/robots.txt /home/sf-bike-dock/public/

ADD public/dist /home/sf-bike-dock/public/dist/


ADD gruntfile.js /home/sf-bike-dock/
ADD .csslintrc /home/sf-bike-dock/
ADD .jshintrc /home/sf-bike-dock/

ENV NODE_ENV docker

# Port 3000 for server
EXPOSE 3000
CMD ["grunt"]
